/**
 * THIS IS AN AUTOGENERATED FILE
 * DO NOT MODIFY THIS FILE NOR ANY OF THE IMPORTED COMPONENTS MANUALLY
 * USE THE THEME GENERATOR COMMAND TO REGENERATE IT
 */

import { lazy } from "react";

export const ArrowDown = lazy(() => import("./ui/ArrowDown"));

export const ArrowLeft = lazy(() => import("./ui/ArrowLeft"));

export const ArrowRight = lazy(() => import("./ui/ArrowRight"));

export const ArrowUp = lazy(() => import("./ui/ArrowUp"));

export const Calendar = lazy(() => import("./ui/Calendar"));

export const CalenderCheck = lazy(() => import("./ui/CalenderCheck"));

export const Check = lazy(() => import("./ui/Check"));

export const Close = lazy(() => import("./ui/Close"));

export const Compare = lazy(() => import("./ui/Compare"));

export const Download = lazy(() => import("./ui/Download"));

export const Drag = lazy(() => import("./ui/Drag"));

export const Expand = lazy(() => import("./ui/Expand"));

export const External = lazy(() => import("./ui/External"));

export const Facebook = lazy(() => import("./social-media/Facebook"));

export const Filter = lazy(() => import("./ui/Filter"));

export const FilterBars = lazy(() => import("./ui/FilterBars"));

export const FilterTwo = lazy(() => import("./ui/FilterTwo"));

export const Gallery = lazy(() => import("./ui/Gallery"));

export const Grid = lazy(() => import("./ui/Grid"));

export const HamburgerMenu = lazy(() => import("./ui/HamburgerMenu"));

export const Home = lazy(() => import("./ui/Home"));

export const Info = lazy(() => import("./ui/Info"));

export const InfoAlt = lazy(() => import("./ui/InfoAlt"));

export const InfoSolid = lazy(() => import("./ui/InfoSolid"));

export const Instagram = lazy(() => import("./social-media/Instagram"));

export const Layers = lazy(() => import("./ui/Layers"));

export const List = lazy(() => import("./ui/List"));

export const Magnify = lazy(() => import("./ui/Magnify"));

export const Mail = lazy(() => import("./ui/Mail"));

export const Map = lazy(() => import("./ui/Map"));

export const Minus = lazy(() => import("./ui/Minus"));

export const Moon = lazy(() => import("./ui/Moon"));

export const OpenQuote = lazy(() => import("./ui/OpenQuote"));

export const PauseVideo = lazy(() => import("./ui/PauseVideo"));

export const Phone = lazy(() => import("./ui/Phone"));

export const Picture = lazy(() => import("./ui/Picture"));

export const Pinterest = lazy(() => import("./social-media/Pinterest"));

export const PlayVideo = lazy(() => import("./ui/PlayVideo"));

export const PlayVideoNoOutline = lazy(() => import("./ui/PlayVideoNoOutline"));

export const Plus = lazy(() => import("./ui/Plus"));

export const Search = lazy(() => import("./ui/Search"));

export const Share = lazy(() => import("./ui/Share"));

export const Star = lazy(() => import("./ui/Star"));

export const Sun = lazy(() => import("./ui/Sun"));

export const ThreeD = lazy(() => import("./ui/ThreeD"));

export const Tool = lazy(() => import("./ui/Tool"));

export const Twitter = lazy(() => import("./social-media/Twitter"));

export const Vector = lazy(() => import("./ui/Vector"));

export const Wrench = lazy(() => import("./ui/Wrench"));

export const YouTube = lazy(() => import("./social-media/YouTube"));

export type AvailableIcons =
	| "ArrowDown"
	| "ArrowLeft"
	| "ArrowRight"
	| "ArrowUp"
	| "Calendar"
	| "CalenderCheck"
	| "Check"
	| "Close"
	| "Compare"
	| "Download"
	| "Drag"
	| "Expand"
	| "External"
	| "Facebook"
	| "Filter"
	| "FilterBars"
	| "FilterTwo"
	| "Gallery"
	| "Grid"
	| "HamburgerMenu"
	| "Home"
	| "Info"
	| "InfoAlt"
	| "InfoSolid"
	| "Instagram"
	| "Layers"
	| "List"
	| "Magnify"
	| "Mail"
	| "Map"
	| "Minus"
	| "Moon"
	| "OpenQuote"
	| "PauseVideo"
	| "Phone"
	| "Picture"
	| "Pinterest"
	| "PlayVideo"
	| "PlayVideoNoOutline"
	| "Plus"
	| "Search"
	| "Share"
	| "Star"
	| "Sun"
	| "ThreeD"
	| "Tool"
	| "Twitter"
	| "Vector"
	| "Wrench"
	| "YouTube";
